
services:
  postgres:
    image: postgres:15
    container_name: dv-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: declaration_db
    ports:
      - "5432:5432"

  etl:
    build:
      context: .
      dockerfile: Dockerfile.etl
    container_name: dv-etl
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/declaration_db
      PYTHONUTF8: "1"
    volumes:
      - .:/app
    command: python ETL.py

  exporter:
    build:
      context: .
      dockerfile: Dockerfile.exporter
    container_name: dv_exporter
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/declaration_db
      CLICKHOUSE_HOST: 'rc1b-dghi9mds291db82e.mdb.yandexcloud.net'
      CLICKHOUSE_PORT: 8443
      CLICKHOUSE_USER: 'admin'
      CLICKHOUSE_PASSWORD: '21041984'
      CLICKHOUSE_SECURE: 'true'
      PYTHONUTF8: "1"
    volumes:
      - .:/app
    command: python export_to_clickhouse.py
