version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: dv-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: declaration_db
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dv-etl
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/declaration_db
      PYTHONUTF8: "1"

volumes:
  postgres_data: